spring:
  application:
    name: authservice
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    open-in-view: false
  data:
    web:
      pageable:
        serialization-mode: via-dto
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/authService?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    hikari:
      minimum-idle: 1
      connection-timeout: 60000
      pool-name: SystemPool
      leak-detection-threshold: 10000
      idle-timeout: 120000
    type: com.zaxxer.hikari.HikariDataSource

# Test Purposes.
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 300000 # 5 mins.
  token-type: "Bearer"
  refresh-token-expiration: 604800 # 7 days
  refresh-token-path: /api/v1/auth/refresh

# logging:
#   level:
#     root: INFO
#     org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: DEBUG
#     liquibase: DEBUG
